# Generated by Django 5.2.7 on 2025-10-27 02:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo Financiero',
                'verbose_name_plural': 'Objetivos Financieros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('para_gastar_dia', models.DecimalField(decimal_places=2, help_text='Presupuesto diario', max_digits=10)),
                ('alimento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('productos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ahorro_y_deuda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sobrante_monetario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Financiero',
                'verbose_name_plural': 'Registros Financieros',
                'ordering': ['-fecha'],
            },
        ),
    ]
