# Generated by Django 5.2.7 on 2025-10-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanciero',
            name='ahorro_y_deuda_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='alimento_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='sobrante_fijo',
            field=models.BooleanField(default=False),
        ),
    ]
