# Generated by Django 5.2.7 on 2025-11-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_registrofinanciero_ahorro_y_deuda_fijo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanciero',
            name='para_gastar_dia',
            field=models.DecimalField(decimal_places=2, help_text='Presupuesto disponible para el día', max_digits=10),
        ),
    ]
